services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/src/:/var/www/src/
    ports:
      - 8000:8000
    tty: true
    command: php artisan serve --host "0.0.0.0"

  db:
    image: mysql:8.0
    volumes:
      - db_store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/export
      - ./minio/config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY} 
    command: server /export --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY:-minio} ${MINIO_SECRET_KEY:-minio123}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/${AWS_BUCKET:-mybucket};
      /usr/bin/mc policy download myminio/${AWS_BUCKET:-mybucket};
      exit 0;
      "

volumes:
  db_store: